//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public Nullable<int> OrderID { get; set; }
        public int OrderItemID { get; set; }
        public string Description { get; set; }
        public Nullable<double> Price { get; set; }
        public int Quantity { get; set; }
    }
}
